---

- name: Install system components
  hosts: all

  pre_tasks:
    - name: Disable selinux
      selinux:
        state: disabled

    - name: Install authorized keys
      authorized_key:
        user: "{{ ansible_user }}"
        key: "{{ item }}"
      loop:
        - https://github.com/natefoo.keys
        - https://github.com/nekrut.keys

  roles:
    - role: galaxyproject.repos
      #tags: slurm

    # FIXME: running patches for GxITs
    #- role: galaxyproject.cvmfs
    #  #tags: cvmfs

    - role: galaxyproject.slurm
      #tags: slurm

  post_tasks:
    - name: Import Docker CE RPM key
      rpm_key:
        key: https://download.docker.com/linux/centos/gpg

    - name: Configure Docker CE yum repository
      yum_repository:
        name: "docker-ce"
        description: "Docker CE Stable - $basearch"
        baseurl: "https://download.docker.com/linux/centos/7/$basearch/stable"
        #gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-Docker-CE"
        gpgcheck: yes
        enabled: yes

    - name: Install Docker CE
      yum:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io

    - name: Create Docker configuration directory
      file:
        path: /etc/docker
        state: directory

    - name: Configure Docker daemon options
      copy:
        content: |
          {
            "storage-driver": "overlay2"
          }
        dest: /etc/docker/daemon.json

    - name: Ensure Docker is started and enabled
      service:
        name: docker
        state: started
        enabled: yes

  tags: system


- name: Install a usegalaxy.org clone
  hosts: galaxyservers

  pre_tasks:
    - name: Install psycopg2
      package:
        name: python-psycopg2

    - name: Create well-known root for certbot
      file:
        path: "{{ certbot_well_known_root }}"
        state: directory

  roles:
    - role: galaxyproject.postgresql
      tags: postgres

    - role: natefoo.postgresql_objects
      become: true
      become_user: postgres
      tags: postgres

    - role: galaxyproject.galaxy
      tags: galaxy

    - role: usegalaxy-eu.gie-proxy
      tags: galaxy

    - role: galaxyproject.nginx
      tags: nginx

  post_tasks:
    - name: Install slurm-drmaa
      package:
        name: slurm-drmaa
      tags: system

    - name: Add nginx to Galaxy group
      user:
        name: nginx
        groups: "{{ galaxy_group.name }}"
      notify:
        - restart nginx
      tags: nginx

    - name: Galaxy post-tasks block
      block:

        - name: Add Galaxy to Docker group
          user:
            name: "{{ galaxy_user }}"
            groups: docker

        - name: Install service unit
          copy:
            src: files/{{ item }}.service
            dest: /etc/systemd/system/{{ item }}.service
          loop:
            - galaxy
            #- galaxy-gxit-proxy
          notify:
            - systemd daemon-reload

        - name: Flush handlers
          meta: flush_handlers

        - name: Ensure Galaxy services are started and enabled
          service:
            name: "{{ item }}"
            state: started
            enabled: yes
          loop:
            - galaxy
            #- galaxy-gxit-proxy

        - name: Create welcome directory
          file:
            path: "{{ galaxy_welcome_dir }}"
            state: directory
            owner: "{{ galaxy_user }}"
            group: "{{ galaxy_group.name }}"

        - name: Copy welcome contents
          synchronize:
            src: files/galaxy/welcome/
            dest: "{{ galaxy_welcome_dir }}"

      tags:
        - galaxy
        - galaxy-post

  handlers:
    - name: restart galaxy
      service:
        name: galaxy
        state: restarted

    - name: systemd daemon-reload
      systemd:
        daemon_reload: yes


- name: Create galaxy user on nodes
  hosts: galaxynodes
  tasks:
    - name: Create galaxy group
      group:
        name: "{{ galaxy_group.name }}"
        gid: "{{ galaxy_group.gid }}"
        system: true

    - name: Create galaxy user
      user:
        name: "{{ galaxy_user.name }}"
        uid: "{{ galaxy_user.uid }}"
        home: "{{ galaxy_user.home }}"
        shell: "{{ galaxy_user.shell }}"
        group: "{{ galaxy_group.name }}"
        groups: docker
        system: true

    - name: Install jq for Epilog script
      package:
        name: jq

    - name: Ensure Epilog script directory exists
      file:
        path: "{{ slurm_config.Epilog |dirname }}"
        state: directory

    - name: Install Epilog script
      copy:
        src: slurm/epilog.sh
        dest: "{{ slurm_config.Epilog }}"
        owner: root
        group: root
        mode: '0755'
