---

- name: galaxyproject.repos
- name: galaxyproject.cvmfs
- name: galaxyproject.slurm
- name: galaxyproject.postgresql
- name: natefoo.postgresql_objects
- name: galaxyproject.galaxy
- name: usegalaxy_eu.certbot
- name: galaxyproject.nginx
- name: usegalaxy_eu.gie_proxy
