---

slurm_roles: controller

certbot_auto_renew_hour: "{{ 23 |random(seed=inventory_hostname)  }}"
certbot_auto_renew_minute: "{{ 59 |random(seed=inventory_hostname)  }}"
certbot_auth_method: --webroot
certbot_install_method: virtualenv
certbot_auto_renew: yes
certbot_auto_renew_user: root
certbot_environment: production
certbot_well_known_root: /srv/nginx/_well-known_root
certbot_share_key_users:
  - nginx
certbot_post_renewal: |
    systemctl restart nginx || true
certbot_domains:
  - "{{ galaxy_server_hostname }}"
certbot_agree_tos: --agree-tos

# NGINX
nginx_selinux_allow_local_connections: true
nginx_servers:
  - clone
nginx_enable_default_server: false
nginx_ssl_servers:
  - clone-ssl
  - clone-gxit-proxy
nginx_conf_http:
  client_max_body_size: 1g
nginx_remove_default_vhost: true
nginx_ssl_role: usegalaxy-eu.certbot
nginx_conf_ssl_certificate: /etc/ssl/certs/fullchain.pem
nginx_conf_ssl_certificate_key: /etc/ssl/user/privkey-nginx.pem

#
# Galaxy
#

#galaxy_gxit_proxy_config_file: "{{ galaxy_config_dir }}/gxit-proxy.yaml"

# used by: galaxy_config var
galaxy_config_id_secret: "{{ vault_galaxy_config_id_secret }}"


## used by: proftpd template and this vars file:
#galaxy_ftp_upload_dir: /galaxy/ftp


## used by: other vars in this vars file
galaxy_log_dir: "/galaxy/log"


postgresql_objects_users:
  - name: galaxy

postgresql_objects_databases:
  - name: galaxy
    owner: galaxy

galaxy_create_user: yes
galaxy_manage_paths: yes
galaxy_manage_clone: no
galaxy_manage_download: no
galaxy_manage_static_setup: yes
galaxy_fetch_dependencies: no
galaxy_manage_mutable_setup: yes
galaxy_manage_database: yes
galaxy_build_client: no
galaxy_manage_errordocs: yes

galaxy_user: galaxy

galaxy_privilege_separation: yes
galaxy_become_users:
  privsep: root
  errdocs: root
  galaxy: galaxy
galaxy_privsep_dirs: []
galaxy_dirs:
  - "{{ galaxy_mutable_data_dir }}"
  - "{{ galaxy_mutable_config_dir }}"
  - "{{ galaxy_cache_dir }}"
  - "{{ galaxy_file_path }}"
  - "{{ galaxy_job_working_directory }}"

galaxy_restart_handler_name: restart galaxy

galaxy_layout: custom
galaxy_cvmfs_repo: main.galaxyproject.org
galaxy_server_dir: /cvmfs/{{ galaxy_cvmfs_repo }}/galaxy
galaxy_shed_tools_dir: /cvmfs/{{ galaxy_cvmfs_repo }}/shed_tools
galaxy_shed_tool_conf_file: /cvmfs/{{ galaxy_cvmfs_repo }}/config/shed_tool_conf.xml
galaxy_tool_dependency_dir: /cvmfs/{{ galaxy_cvmfs_repo }}/deps

galaxy_venv_dir: /cvmfs/{{ galaxy_cvmfs_repo }}/venv
galaxy_config_dir: /galaxy/config
galaxy_config_file: "{{ galaxy_config_dir }}/galaxy.yaml"
galaxy_config_style: yaml
galaxy_mutable_data_dir: /galaxy/var
galaxy_mutable_config_dir: "{{ galaxy_mutable_data_dir }}/config"
galaxy_job_working_directory: /galaxy/jobs
galaxy_file_path: /galaxy/data

galaxy_admin_email_to: galaxy-bugs@galaxyproject.org

## used by: galaxyproject.galaxy
nginx_srv: /srv/nginx/galaxy
galaxy_errordocs_dest: "{{ nginx_srv }}/error"
galaxy_errordocs_502_message: |
  You are seeing this message because a request to Galaxy timed out or was refused. This may be a temporary issue which
  could be resolved by retrying the operation you were performing. If you receive this message repeatedly or for an
  extended amount of time, please report it to the Galaxy Team at
  <a href='mailto:galaxy-bugs@galaxyproject.org'>galaxy-bugs@galaxyproject.org</a>
  with details on what you were trying to do and the URL in the address bar. More information on the current state of
  Galaxy services may be available on the
  <a href="https://status.galaxyproject.org/">Galaxy status page</a>
  or the
  <a href="https://twitter.com/galaxyproject">@galaxyproject Twitter feed</a>.



## used by playbook
galaxy_welcome_dir: "{{ nginx_srv }}/welcome"


## used by usegalaxy_privileged and templating job_conf.xml
#galaxy_dynamic_rule_dir: "{{ galaxy_root }}/dynamic_rules"


## used by: galaxyproject.galaxy
galaxy_config:
  uwsgi:
    master: true
    processes: 8
    threads: 4
    single-interpreter: true
    thunder-lock: true
    harakiri: 600
    buffer-size: 16384
    #log-maxsize: 134217728
    #log-master-bufsize: 15865856
    pythonpath: lib
    module: galaxy.webapps.galaxy.buildapp:uwsgi_app_factory()
    socket: 127.0.0.1:4001
    mule:
      - lib/galaxy/main.py
      - lib/galaxy/main.py
      - lib/galaxy/main.py
      - lib/galaxy/main.py
    farm: job-handlers:1,2,3,4

  galaxy:

    logging:
      disable_existing_loggers: false
      filters:
        stack:
          (): galaxy.web_stack.application_stack_log_filter
      formatters:
        stack:
          (): galaxy.web_stack.application_stack_log_formatter
      handlers:
        console:
          class: logging.StreamHandler
          filters:
          - stack
          formatter: stack
          level: DEBUG
          stream: ext://sys.stderr
        files:
          class: logging.FileHandler
          filters:
          - stack
          level: DEBUG
          formatter: stack
          filename: /galaxy/var/galaxy_default.log
          filename_template: /galaxy/var/galaxy_{pool_name}_{server_id}.log
      loggers:
        amqp:
          level: INFO
          qualname: amqp
        paste.httpserver.ThreadPool:
          level: WARN
          qualname: paste.httpserver.ThreadPool
        routes.middleware:
          level: WARN
          qualname: routes.middleware
      root:
        handlers:
        - files
        level: DEBUG
      version: 1

    # this can be removed after 9/22 and the datatypes_conf.xml update
    gbrowse_display_sites: wormbase,tair,modencode_worm,modencode_fly
    ucsc_display_sites: main,archaea,ucla

    # secrets

    database_connection: "postgresql:///galaxy"
    install_database_connection: "sqlite:////cvmfs/main.galaxyproject.org/var/galaxy_main_install.sqlite?isolation_level=IMMEDIATE"
    id_secret: "{{ galaxy_config_id_secret }}"
    admin_users: "nate@bx.psu.edu,mo@galaxyproject.org"

    # paths

    file_path: "{{ galaxy_file_path }}"
    new_file_path: "{{ galaxy_mutable_data_dir }}/tmp"
    tool_config_file: "{{ galaxy_config_dir }}/tool_conf.xml,{{ galaxy_shed_tool_conf_file }}"
    tool_dependency_dir: "{{ galaxy_tool_dependency_dir }}"
    job_working_directory: "{{ galaxy_job_working_directory }}"
    tool_data_path: "{{ galaxy_mutable_data_dir }}/tool-data"
    #nginx_upload_store: /galaxy-repl/main/upload
    #nginx_upload_job_files_store: /galaxy-repl/main/upload_job_files
    #ftp_upload_dir: "{{ galaxy_ftp_upload_dir }}"
    #user_library_import_dir: /galaxy-repl/main/ftp
    #library_import_dir: /galaxy-repl/main/import
    #galaxy_data_manager_data_path: /galaxy-repl/manageddata/data

    tool_sheds_config_file: "{{ galaxy_config_dir }}/tool_sheds_conf.xml"
    tool_data_table_config_path: "{{ galaxy_config_dir }}/tool_data_table_conf.xml,/cvmfs/data.galaxyproject.org/byhand/location/tool_data_table_conf.xml,/cvmfs/data.galaxyproject.org/managed/location/tool_data_table_conf.xml"
    build_sites_config_file: "{{ galaxy_config_dir }}/build_sites.yml"
    ##datatypes_config_file: "{{ galaxy_config_dir }}/datatypes_conf.xml"
    #object_store_config_file: "{{ galaxy_config_dir }}/object_store_conf.xml"
    job_config_file: "{{ galaxy_config_dir }}/job_conf.xml"
    #workflow_schedulers_config_file: "{{ galaxy_config_dir }}/workflow_schedulers_conf.xml"
    #job_resource_params_file: "{{ galaxy_config_dir }}/job_resource_params_conf.xml"
    data_manager_config_file: "{{ galaxy_config_dir }}/data_manager_conf.xml"
    job_metrics_config_file: "{{ galaxy_config_dir }}/job_metrics_conf.xml"
    dependency_resolvers_config_file: "{{ galaxy_config_dir }}/dependency_resolvers_conf.xml"

    migrated_tools_config: "/cvmfs/main.galaxyproject.org/config/migrated_tools_conf.xml"
    shed_tool_data_table_config: "/cvmfs/main.galaxyproject.org/config/shed_tool_data_table_conf.xml"
    shed_data_manager_config_file: "/cvmfs/main.galaxyproject.org/config/shed_data_manager_conf.xml"
    integrated_tool_panel_config: "{{ galaxy_mutable_config_dir }}/integrated_tool_panel.xml"
    sanitize_whitelist_file: "{{ galaxy_mutable_config_dir }}/sanitize_whitelist.txt"

    #containers_config_file: "{{ galaxy_config_dir }}/containers.yml"
    #enable_beta_containers_interface: "True"

    ##environment_setup_file: /galaxy/main/job_env.bash

    builds_file_path: "/cvmfs/data.galaxyproject.org/managed/location/builds.txt"
    ucsc_build_sites: "/cvmfs/data.galaxyproject.org/managed/location/ucsc_build_sites.txt"

    # interactive environments
    #interactive_environment_plugins_directory: "{{ galaxy_root }}/interactive_environments/plugins"
    #dynamic_proxy_manage: "False"
    #dynamic_proxy_session_map: /srv/galaxy/main/var/gie_proxy_session_map.sqlite
    #dynamic_proxy_bind_port: 4280
    #dynamic_proxy_bind_ip: 0.0.0.0
    #dynamic_proxy_debug: "True"
    #dynamic_proxy_external_proxy: "True"
    #dynamic_proxy_prefix: gie_proxy
    galaxy_infrastructure_url: https://{{ galaxy_server_hostname }}
    ##trust_ipython_notebook_conversion: "True"


    # general stuff

    database_engine_option_pool_size: 10
    database_engine_option_max_overflow: 20
    database_engine_option_server_side_cursors: "True"
    manage_dependency_relationships: "False"
    len_file_path: /cvmfs/data.galaxyproject.org/managed/len/ucsc
    collect_outputs_from: job_working_directory
    smtp_server: localhost
    error_email_to: galaxy-bugs@galaxyproject.org
    #user_activation_on: "True"
    #activation_email: "Galaxy Activation <activate@galaxyproject.org>"
    #activation_grace_period: 6
    instance_resource_url: "https://galaxyproject.org/support"
    screencasts_url: "https://vimeo.com/galaxyproject"
    search_url: "https://galaxyproject.org/search/"
    blacklist_file: "{{ galaxy_config_dir }}/disposable_email_blacklist.conf"
    inactivity_box_content: "Your account has not been activated yet.  Feel free to browse around and see what's available, but you won't be able to upload data or run jobs until you have verified your email address."
    helpsite_url: "https://help.galaxyproject.org/"
    wiki_url: "https://galaxyproject.org/"
    static_enabled: "False"
    #enable_cloud_launch: "True"
    #cloudlaunch_default_ami: ami-a7dbf6ce
    nginx_x_accel_redirect_base: /_x_accel_redirect
    #nginx_upload_path: /_upload
    #nginx_upload_job_files_path: /_job_files
    log_events: "False"
    log_actions: "False"
    debug: "False"
    use_interactive: "False"
    use_pbkdf2: "True"
    allow_user_deletion: "True"
    allow_user_dataset_purge: "True"
    #enable_openid: "True"
    #ftp_upload_site: "ftp://{{ galaxy_instance_hostname }}"
    enable_quotas: "True"
    track_jobs_in_database: "True"
    retry_metadata_internally: "False"
    retry_job_output_collection: 5
    cleanup_job: onsuccess
    monitor_thread_join_timeout: 60
    max_metadata_value_size: 1000000
    tool_search_limit: 30
    tool_name_boost: 12
    tool_section_boost: 5

    conda_prefix: "/cvmfs/main.galaxyproject.org/deps/_conda"

    mulled_resolution_cache_data_dir: "{{ galaxy_mutable_data_dir }}/mulled/data"
    mulled_resolution_cache_lock_dir: "{{ galaxy_mutable_data_dir }}/mulled/lock"

    # For handler heartbeats
    #use_heartbeat: "True"
    #heartbeat_interval: "-1"
    #heartbeat_log: "{{ galaxy_log_dir }}/heartbeat_{server_name}_{pid}.log"

    # stats
    #statsd_host: "127.0.0.1"
    #statsd_port: "8125"
    #statsd_prefix: "main"

    # start high, decrease when we've fixed things
    #slow_query_log_threshold: "2"

    # https://github.com/galaxyproject/usegalaxy-playbook/issues/211
    legacy_eager_objectstore_initialization: "True"

    allow_user_impersonation: "True"
    interactivetools_enable: "True"
    interactivetools_map: "{{ gie_proxy_sessions_path }}"

    brand: Workshop

# specifies config files to copy from the playbook
galaxy_config_files:
  - src: files/galaxy/config/tool_data_table_conf.xml
    dest: "{{ galaxy_config_dir }}/tool_data_table_conf.xml"
  - src: files/galaxy/config/tool_conf.xml
    dest: "{{ galaxy_config_dir }}/tool_conf.xml"
  - src: files/galaxy/config/data_manager_conf.xml
    dest: "{{ galaxy_config['galaxy']['data_manager_config_file'] }}"
  - src: files/galaxy/config/tool_sheds_conf.xml
    dest: "{{ galaxy_config['galaxy']['tool_sheds_config_file'] }}"
  - src: files/galaxy/config/job_metrics_conf.xml
    dest: "{{ galaxy_config['galaxy']['job_metrics_config_file'] }}"
  #- src: files/galaxy/config/job_resource_params_conf.xml
  #  dest: "{{ galaxy_config['galaxy']['job_resource_params_file'] }}"
  - src: files/galaxy/config/dependency_resolvers_conf.xml
    dest: "{{ galaxy_config['galaxy']['dependency_resolvers_config_file'] }}"
  - src: files/galaxy/config/disposable_email_blacklist.conf
    dest: "{{ galaxy_config['galaxy']['blacklist_file'] }}"

# specifies config files to template from the playbook
galaxy_config_templates:
  - src: templates/galaxy/config/job_conf.xml.j2
    dest: "{{ galaxy_config_dir }}/job_conf.xml"
  - src: templates/galaxy/config/build_sites.yml.j2
    dest: "{{ galaxy_config['galaxy']['build_sites_config_file'] }}"
  #- src: templates/galaxy/config/gxit-proxy.yaml.j2
  #  dest: "{{ galaxy_gxit_proxy_config_file }}"

# doesn't overwrite if it already exists
galaxy_mutable_config_templates:
  - src: templates/galaxy/config/integrated_tool_panel.xml.j2
    dest: "{{ galaxy_config['galaxy']['integrated_tool_panel_config'] }}"
  - src: templates/galaxy/config/sanitize_whitelist.txt.j2
    dest: "{{ galaxy_config['galaxy']['sanitize_whitelist_file'] }}"

#
# GIE/T Proxy
#

gie_proxy_dir: /srv/gie-proxy/proxy
gie_proxy_git_repo: https://github.com/natefoo/gie-nodejs-proxy.git
gie_proxy_git_version: ie2-log-fix
gie_proxy_setup_nodejs: nodeenv
gie_proxy_nodejs_version: "10.13.0"
gie_proxy_virtualenv: /srv/gie-proxy/venv
gie_proxy_setup_service: systemd
gie_proxy_port: 4002
gie_proxy_verbose: true
gie_proxy_sessions_path: "{{ galaxy_mutable_data_dir }}/interactivetools_map.sqlite"
